"""empty message

Revision ID: c60d7b68a8ca
Revises: 8adc6efc9b58
Create Date: 2018-08-11 17:42:55.586854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c60d7b68a8ca'
down_revision = '8adc6efc9b58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('author', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_post_author'), 'post', ['author'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_author'), table_name='post')
    op.drop_column('post', 'author')
    # ### end Alembic commands ###
